import React from 'react'

export default {
  products: [
    {
      _id: "1234",
      name: "slim hood",
      category: "hood",
      image: "/images/afro.jpg",
      price: "KES 1800",
      brand: "Nike",
      rating: "4.5",
      numReview: 10,
    },
    {
      _id: "1244",
      name: "kenya hood",
      category: "hood",
      image: "/images/d3.jpg",
      price: "KES 2500",
      brand: "Champion",
      rating: "4.4",
      numReview: 10,
    },
    {
      _id: "15457",
      name: "Tiger hood",
      category: "hood",
      image: "/images/d1.jpg",
      price: "KES 2100",
      brand: "Spandex",
      rating: "4.8",
      numReview: 10,
    },
    {
      _id: "1254874",
      name: "AIR FORCE",
      category: "hoods",
      image: "/images/d1.jpg",
      price: "KES 2300",
      brand: "Nike",
      rating: "4.5",
      numReview: 10,
    },
    {
      _id: "154564",
      name: "Magic hood",
      image: "/images/d1.jpg",
      price: "KES 1500",
      brand: "Nike",
      rating: "4.5",
      review: 10,
    },
  ],
};
